# Generated by Django 3.2.3 on 2021-05-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='d_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='network',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='measurement',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='u_speed',
            field=models.FloatField(default=0),
        ),
    ]
